== vertx-forge-addon
:idprefix: id_ 

This JBoss Forge addon lets you create Vert.x projects.

It let you:

* create new Vert.x project
* add verticles in Java, Groovy, JavaScript and Ruby

In the current state it only support Maven and the generated project is packaged as a _fat jar_.
        
=== Installation

```
addon-install --coordinate me.escoffier.forge:vertx-forge-addon
```

=== Create project

To create a project, just create a _Maven_ project packaged as a _jar_ file, without a _technical stack_:

```
[tmp]$ project-new
***INFO*** Required inputs not satisfied, entering interactive mode
* Project name:  some-project
? Top level package [org.some.project]:  org.acme
? Version [1.0.0-SNAPSHOT]:
? Final name:
? Project location [/Users/clement/tmp]:

[0] (x) war
[1] ( ) jar
[2] ( ) parent
[3] ( ) forge-addon
[4] ( ) resource-jar
[5] ( ) ear
[6] ( ) from-archetype
[7] ( ) generic

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Project type: [0-7] 1

[0] (x) Maven

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Build system: [0]

[0] ( ) JAVA_EE_7
[1] ( ) JAVA_EE_6
[2] ( ) NONE

Press <ENTER> to confirm, or <CTRL>+C to cancel.
? Stack (The technology stack to be used in this project): [0-2] 2
***SUCCESS*** Project named 'some-project' has been created.
```

Then, add vert.x to the project using:

```
vertx-setup
```

Here you go you have your vert.x project with a java verticle

=== Build and Run

Build the project using:

```
build
```

Run it using:

```
build org.codehaus.mojo:exec-maven-plugin:exec@run
```

Hit `CTRL+C` to quit the application


=== Add verticle

You can add a verticle using:

```
vertx-add-verticle --main --name=MyVerticle.js
```

`--main` describes whether or not the verticle is going to be the `main-verticle` of the application.
`name` define the name of the verticle, the type is detected from the extension.

The addon configures the project to use the right dependencies and directory structure.